### ISSUE TITLE
#0

### ISSUE THREAD

**Issue by felipe-santos** [oumoussa98/vue3-infinite-loading#1]

**Comment by gustawdaniel-acaisoft** [comment]
can you improve docs?

Add more minimal and complex examples?

I feel that code in example is too complex, but in in docs do not contains all elements like template in App. Additionally it would be great if we will have examples without composition api too.

**Comment by oumoussa98** [comment]
Hello @gustawdaniel-acaisoft, a new docs based on vitepress will be available soon
And i'll consider adding more examples
