### ISSUE TITLE
Infinite function arguments

### ISSUE THREAD

**Issue by hellagirrl** [oumoussa98/vue3-infinite-loading#13]
Hi! Can I add more arguments (like params of axios request) to infinite function? I have to implement infinite loading on two tables that I get access to by clicking on one of the tabs. Each table load data based on query params of axios request. What I mean is:
```
// ...
const load = async ($state, param) => {
    const res = await axios.get('/user', 'param', page)
    // ......
}
```
Every time I add the second argument, I get an error: ``` $state.loaded() is not a function ```. In DevTools watch list I get this: ``` $state: 'param' ```. Is there somethin I can do to fix this?

**Comment by yangxuhui** [comment]
@hellagirrl You could create the `param` data attribute within your component, then use the `param` inside your infinite function
