### ISSUE TITLE
Execute @infinite event on page load

### ISSUE THREAD

**Issue by nmdgent-jefverme** [oumoussa98/vue3-infinite-loading#16]
Hello

Is there anyway to fire the infinite event when the page is loaded? I'm using the infinite loader in a mobile app and when the component is not yet in my viewport, the @infinite event is fired when I scroll down to the component. The problem is that some text is depending on the content of my infinite loader, so I'm looking for a way to load the data when the page is loaded. I allready tried to play arround with the firstLoad prop and I tried to call my loadData function onMounted which resulted in a to many requests error from my api

**Comment by yangxuhui** [comment]
The `@infinite` event will be fired when the page is loaded, if you set the the `firstLoad` prop to `false`, then the component will not handle first load. @nmdgent-jefverme
