### ISSUE TITLE
How to use with Vuejs 2 template

### ISSUE THREAD

**Issue by stoneC0der** [oumoussa98/vue3-infinite-loading#18]
Hi, can anyone point me into the right direction, like sample code, examples

I recently learned (or still learning vuejs) but I have not started using the composition API of Vuejs 3 so I am still using the old template syntax and I have trouble implemented this plugin

I have already refactored a plugin that use composition API by default to use Vue2 template syntax but can seem to get this one working:

What I facing is as follow:

- The firstLoad function is not triggered so I have to manually call the handleLoading function in the created or mounted hook
- Bu doing so, I got ***$state.loaded()*** is not a function

A quick answer will be appreciated from anyone as it feature that I need to implement before i can move on with the project.
Thanks

**Comment by oumoussa98** [comment]
Hi @stoneC0der, If you are using vue 3 typically should work  as you'd expect even with options API
I don't know what might cause that problem, if you can provide more info and code example would help solve the issue.
Here is a simple working [example](https://codesandbox.io/s/infinite-loading-j1f96x?file=/src/main.js) using options API, Hope it helps.
