### ISSUE TITLE
doesn't have "type": "module"

### ISSUE THREAD

**Issue by giribabu1997** [oumoussa98/vue3-infinite-loading#20]
v3-infinite-loading doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

**Comment by oumoussa98** [comment]
hi @giribabu1997, please elaborate more on the issue.
And how can we reproduce the same error.

**Comment by giribabu1997** [comment]
in vue3 SSR application I'm getting this issue.

**Comment by giribabu1997** [comment]
hi @oumoussa98, 
in vue3 SSR application I'm getting this error.

**Comment by oumoussa98** [comment]
I am unable to reproduce this
If you manage to find a repro case, we would gladly reopen this issue.
