### ISSUE TITLE
not scroll active firstLoad when f5 browser. you can add original trigger function make it better.

### ISSUE THREAD

**Issue by hoanghiep1x0** [oumoussa98/vue3-infinite-loading#22]
i found it working fine but lack of trigger function from call first scroll example setup. each time: the router's id changes.
This is a reset component issue. Similar is an Identity problem. using Identity but not working in my case. When reloading the component with f5 from the browser, it doesn't automatically fire the component with firstLoad. So I need a trigger call from watch route.params.slug=> refetchData.

Like triggering infinite scroll loading from setup with watch(()=> route.params.slug,Active-Scroll-Loading).

I have this piece of code but f5 it doesn't run firstLoad.

`<pre><template>

    <div class="tag tag-content">

        <h1 v-if="tag != null" class="mb-10">{{ tag.name }} <span class="fs-5 text-muted">{{ `(${tag.use})` }}</span>
        </h1>

        <div class="d-flex gap-3 flex-wrap" v-if="tags && tags.length">
            <router-link v-for="(tag, i) in tags" :key="i" :to="{
                name: 'discussion-by-tag',
                params: {
                    id: tag.slug
                }
            }" class="btn btn-flex btn-sm btn-color-gray-500 btn-bg-light btn-active-primary px-4 h-30px ">
                {{ tag.name }}
                {{ `(${tag.use})` }} </router-link>
        </div>

        <div v-else class="text-center">

            <div class="flex-grow-1 bgi-no-repeat bgi-size-contain bgi-position-x-center card-rounded-bottom h-200px mh-200px my-5 mb-lg-12"
                style="background-image:url('media/illustrations/sketchy-1/5.png')">
            </div>
            {{ t("data_empty") }}
        </div>

    </div>

    <div class="separator separator-dashed border-gray-300 my-6"></div>

    <div v-if="questions && questions.length" v-for="(question, i) in questions" :key="i">
        <Questions :data="question" />
    </div>
    <div v-else class="text-center">
        <div class="flex-grow-1 bgi-no-repeat bgi-size-contain bgi-position-x-center card-rounded-bottom h-200px mh-200px my-5 mb-lg-12"
            style="background-image:url('media/illustrations/sketchy-1/5.png')">
        </div>
        {{ t("data_empty") }}
    </div>

    <infinite-loading ref="scrollComponent" :identifier="route.params.id" :firstLoad="true" @infinite="infiniteHandler">
        <template #complete>
            <p class="text-center"> {{ t("no_results") }}</p>
        </template>
        <template #spinner>
            <div class="d-flex align-items-center mt-5 ">
                <span class="spinner-border text-primary" role="status"></span>
                <span class="text-muted fs-6 fw-bold ms-5">Loading...</span>
            </div>

        </template>

    </infinite-loading>

</template>

<script>
import { defineComponent, onMounted, ref, computed, watch, watchEffect } from "vue";
import Questions from "@/views/community/discussion/Questions";
import InfiniteLoading from "v3-infinite-loading";
import "v3-infinite-loading/lib/style.css";
import LayoutService from "@/core/services/LayoutService";
import { useI18n } from "vue-i18n/index";
import { useRoute } from 'vue-router';
import { useStore } from "vuex";
import { Actions, Mutations } from "@/store/enums/StoreEnums";
export default defineComponent({
    name: "dev-discussion-all",
    components: { Questions, InfiniteLoading },
    setup() {

        const { t } = useI18n();
        const store = useStore();
        const scrollComponent = ref(null);
        const route = useRoute();
        const questions = ref([]);

        const tags = ref([]);
        const tag = ref({});
        const data = computed(() => store.getters.questionListByTag);

        onMounted(() => {
            if (!localStorage.getItem("config")) {
                LayoutService.enableSidebar();
            }
        })

        // created
        //---- Load ALL TAGS
        store.dispatch(Actions.LIST_TAG_ALL).then(result => {
            tags.value = result;
        })
        // reset store pagination list by tag
        const firstLoad = async () => {
            await store.commit(Mutations.RESET_LIST_BY_TAG)
            // fetch data by tags
            await store.dispatch(Actions.LIST_QUESTION_BY_TAG, {
                slug: route.params.id,
                payload: {
                    page: data.value.page,
                    limit: data.value.limit
                }
            }).then(result => {
                questions.value = result.rows;
                tag.value = result.tag;
            })
        }

        firstLoad();

        //function  reload data
        const fetchPage = async () => {
            let result = await store.dispatch(Actions.LIST_QUESTION_BY_TAG, {
                slug: route.params.id,
                payload: {
                    page: data.value.page,
                    limit: data.value.limit
                }
            });
            tag.value = result.tag;
        }

        // check router changer reload
        watch(() => route.params.id, async () => {
            await store.commit(Mutations.RESET_LIST_BY_TAG);
            await fetchPage();
        });

        // set data when computed changer 
        watchEffect(() => {
            questions.value = data.value.rows;
            tag.value = data.value.tag;
        })

        const infiniteHandler = async ($state) => {
            try {
                if (data.value.page <= data.value.pages) {
                    await fetchPage();
                    $state.loaded();
                } else {
                    $state.complete();
                }
            } catch (error) {
                $state.error();
            }
        }

        return {
            t,
            scrollComponent,
            route,
            tag,
            tags,
            questions,
            infiniteHandler
        }

    },
});
</script>

</pre>`

**Comment by oumoussa98** [comment]
I am unable to reproduce this
If you manage to find a repro case, we would gladly reopen this issue.
