### ISSUE TITLE
ScrollTop error

### ISSUE THREAD

**Issue by tunjixy** [oumoussa98/vue3-infinite-loading#36]
Hi, thanks for the work on this library

I'm getting error while scrolling to the top since the last update, below is the error message, i'll be glad if you can help.

v3-infinite-loading.mjs:69 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'scrollTop') at v3-infinite-loading.mjs:69:32

**Comment by oumoussa98** [comment]
I managed to reproduce the same error, thanks for reporting

**Comment by mahouha** [comment]
Hi, How are you used the scroll top ? I try to use this but it stay scrolling from top to bottom <br>
   ` <InfiniteLoading @infinite="load" :top="true" />`
