### ISSUE TITLE
Does not seem to work on mobile when target is default

### ISSUE THREAD

**Issue by sarik-k** [oumoussa98/vue3-infinite-loading#4]
I used it on my app with default target (window) and it doesn't work on phones (works on browser emulating phones though). 

Tested on Chrome and Firefox. 

https://gfycat.com/fearfulhopefulgossamerwingedbutterfly

**Comment by oumoussa98** [comment]
Hello @sarik-k, thanks for the detailed report.
You might just need to adjust the distance property to make it work for now
And I'll see how can we fix the issue later on
