### ISSUE TITLE
Code fetches all the comments instead of loading them on scroll

### ISSUE THREAD

**Issue by nicklegroe** [oumoussa98/vue3-infinite-loading#40]
Hello,

I created a basic example of loading comments, when I specify a target it loads all the comments instead of loading on scroll, I need to specify a target because in the end I will have multiple instances on the same page (3 col layout).

Can you check what I'm doing wrong?

https://codesandbox.io/s/vue3-infinite-loading-u132fs?file=/src/App.vue

**Comment by oumoussa98** [comment]
Hello @nicklegroe
You need to set a fixed height for the target, and make it scrollable like so:
```css
.open {
  height: 100vh;
  overflow-y: auto;
}
```
