### ISSUE TITLE
Multiple <infinite-loading> on the same page

### ISSUE THREAD

**Issue by mikelerch** [oumoussa98/vue3-infinite-loading#41]
I'm using this package for a Kanban board I built, which has 3 columns. 
Each `<column>` is its own component and has an `<infinite-loading>` component inside, which is scrollable independently. 

On the initial page load, everything works as expected and all 3 columns call their corresponding `@infinite="load"` function, which fetches the first page of data. When scrolling the three columns, they also continue to load more pages, which is perfect.

However, the same page contains an input field to perform a search. When a search is done, I'm using the Provide / Inject functionality of Vue3 to pass the search query to each `<column>` component. This also works and all 3 components receive the search string.

In order to refresh each column, I make use of the `:identifier="id"` prop of the `<infinite-loading>` component. According to the docs, it should cause a reset and result in the `@infinite="load"` function being called again. However, only 2 columns seem to load the new data after performing the first search and only 1 column after performing a second or third search.

The `:id` to reset the component is a new `+new Date()` everytime the search changes.

If needed, I could put together a codesandbox for further testing, but do you have any clue why this would happen?

---

I just tried it with another package, and the exact same setup works, only difference being I use the `:key` prop to reset their component. I tried the same with the `<infinite-loading>` one, but it doesn't seem to solve my problem.

This package is the most flexible and maintained one, so I hope I wouldn't want to switch to something else.

**Comment by oumoussa98** [comment]
I have no idea what might cause the problem.
If you can provide a codesandbox for further testing would be perfect.

**Comment by oumoussa98** [comment]
I am unable to reproduce this.
If you manage to find a repro case, we would gladly reopen this issue.
