### ISSUE TITLE
Infinite event not emitting when there is a multiple component on same page

### ISSUE THREAD

**Issue by santhanakrishnanstark** [oumoussa98/vue3-infinite-loading#45]
## Version
1.2.1

## Vue.js version
3.2

### Reproduction Link:
With code-editor: https://codesandbox.io/s/v3-infinite-load-issue-c99j3u?file=/src/App.vue
Fullscreen window: https://c99j3u.csb.app/

### Steps to reproduce:
1. Open the reproduction link where you can see 6 infinite loading component.
2. Now, Scroll down the first card until you see there is "No more result!" message. (While doing this do not scroll down the actual page scroll only the within the card component).
3. After you see the "No more result!" then scroll down to the page.
4. Now, you can able to see that the last infinite loading card are not loading its data :(

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/33591962/199899297-e3b94b5a-9a6c-4617-9746-2b45c9a39496.png">

### What is Expected?
All the infinite loading component should load its data when it's in the visible area.

### What is actually happening?
If any one of the infinite component is completed then it execute the "stopObserver()" function which is "disconnect()" only the last infinite loading component.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/33591962/199900225-4ba1bdf6-3af1-4780-9026-d98eec879c01.png">

The observer doesn't track which one is completed and which one is needed to be observe. Always the last one is getting disconnect().

**Comment by oumoussa98** [comment]
Hello @santhanakrishnanstark, thanks for the detailed report.
After investigating the issue it appears that it's caused by the `observer` variable inside utils which is shared between `InfiniteLaoding` instances and when `disconnect` is called the other components get affected as well.
