### ISSUE TITLE
Multi infinite loading for multiple tabs in one page

### ISSUE THREAD

**Issue by vuongutc** [oumoussa98/vue3-infinite-loading#50]
I have a problem.
when i use v3-infinite-loading for multi tabs. in tab 1. is working however when i scroll to if(data.length < per_page) $state.complete() then click "tab 2" it not working even though page 2 has data.length >= per_page

how i can fix this. pl help me. ths!

**Comment by oumoussa98** [comment]
I can't reproduce this, if you can provide a repro case would help a lot.
However, here is a working example with tabs on [stackblitz](https://stackblitz.com/edit/v3-infinite-loading-tabs?file=src/components/Tabs.vue) and works just fine with [keep-alive](https://stackblitz.com/edit/v3-infinite-loading-tabs?file=src/components/Tabs.vue) as well.

_**And please make sure you're using the latest version.**_

**Comment by vuongutc** [comment]
> I can't reproduce this, if you can provide a repro case would help a lot. However, here is a working example with tabs on [stackblitz](https://stackblitz.com/edit/v3-infinite-loading-tabs?file=src/components/Tabs.vue) and works just fine with [keep-alive](https://stackblitz.com/edit/v3-infinite-loading-tabs?file=src/components/Tabs.vue) as well.
> 
> _**And please make sure you're using the latest version.**_

Ths u, it worked.
