### ISSUE TITLE
Can't get :identifier works

### ISSUE THREAD

**Issue by tadvas** [oumoussa98/vue3-infinite-loading#53]
Hi there,

I am exploring a use case for reloading the component. And I am not sure it's a bug. Maybe it's a leak of knowledge.

I've added a simple input to the demo page. And trying to achieve the following behavior: once I change the property in the input  - the infinity scroll gets reloaded/reset.

According to the docs, that should be the case. However, it doesn't work. Where am I wrong?

```
<script setup>
  import { ref } from "vue";
  import InfiniteLoading from "v3-infinite-loading";
  import "v3-infinite-loading/lib/style.css";

  let comments = ref([]);
  let testNumber = 1;
  let page = 1;
  const load = async $state => {
    console.log("loading...");

    try {
      const response = await fetch(
        "https://jsonplaceholder.typicode.com/comments?_limit=10&_page=" + page
      );
      const json = await response.json();
      if (json.length < 10) $state.complete();
      else {
        comments.value.push(...json);
        $state.loaded();
      }
      page++;
    } catch (error) {
      $state.error();
    }
  }; 
</script>
<template>
  <div>
    <input type="number" v-model="testNumber"/>
  </div>
  <div class="result" v-for="comment in comments" :key="comment.id">
    <div>{{ comment.email }}</div>
    <div>{{ comment.id }}</div>
  </div>
  <InfiniteLoading @infinite="load" :identifier="testNumber"/>
</template>
<style>
  #app {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
  }

  .result {
    display: flex;
    flex-direction: column;
    gap: 5px;
    font-weight: 300;
    width: 400px;
    padding: 10px;
    text-align: center;
    margin: 0 auto 10px auto;
    background: #eceef0;
    border-radius: 10px;
  }
</style>
```

**Comment by oumoussa98** [comment]
`identifier` prop expects a reactive variable so you should declare testNumber as follows
```ts
let testNumber = ref(1);
```
And you should clear `comments` variable on each change
Here is an [example on staskblitz](https://stackblitz.com/edit/v3-infinite-loading-tabs-sxfvdo?file=src/App.vue)
even though it calls ` $state.complete()` the infinite event is emitted if the `identifier` changed

**Comment by tadvas** [comment]
@oumoussa98 thanks for the reply
Good catch regarding reactive variable.
But even in example, the component doesn't get reloaded...
Fix me, if I wrong, please

Sorry for bothering you, but it's the best infinity scroll for vue3, so I want to make it work :)

**Comment by tadvas** [comment]
And I mean by reloaded is sending a request to the server to grab new params. I don't see a request.
However, after checking the source code, I don't see an issue as well, so looks like I just need a help(

**Comment by oumoussa98** [comment]
Thank you @tadvas.
I think what you missed here is resetting the `comments` array to get the desired behavior.
Add a watcher to `testNumber` and reset `comments` on each change or better reset the `comments` array
on the load function before fetching new data.
```js
const load = async ($state) => {
  comments.value = [];
  // then fetch new data
};
```
