### ISSUE TITLE
Data not consistently being loaded to the end during scroll (using demo code from docs in Nuxt3 app)

### ISSUE THREAD

**Issue by dosstx** [oumoussa98/vue3-infinite-loading#58]
I am seeing a weird issue where when user is viewing my app in "desktop" mode (non-mobile size viewport), posts are not infinitely loading past page 2. If on mobile view, posts **sometimes** infinitely load correctly to the end. Other times it may load more than 2 pages, but not all the way to the end of the data. 

I've copied the demo provided from the documentation and applied it to a Nuxt 3 app. I am testing it in the Edge browser.

Does anyone know why the posts are not consistently loading to the end of the data? _It should be loading about 10 posts per page for a total of 100, but in my tests, only 2 pages of data is loaded for a total of around 20 posts when user scrolls to bottom_ 

I've got a reproduction available here: https://stackblitz.com/edit/nuxt-starter-2qcayv?file=pages/index.vue

Note: Be sure to click the "Open in New Tab" button at top right to see the issue in action.

**Comment by oumoussa98** [comment]
Fixed in the new version, [checkout this](https://github.com/oumoussa98/vue3-infinite-loading/releases#:~:text=Intersection%20issues%20caused%20by%200px%20height%20%2358)
