### ISSUE TITLE
Error when component already has explicitly named default slot

### ISSUE THREAD

**Issue by fordiquez** [oumoussa98/vue3-infinite-loading#61]
![image](https://user-images.githubusercontent.com/44981513/231637726-62a5ad2f-03ab-4de6-b075-68c79bacdb6f.png)
![image](https://user-images.githubusercontent.com/44981513/231637851-2cb2a8ba-5f21-4d67-9871-d2e38c116848.png)
Hi, I get an error when I try to place a component next to <template #default>

**Comment by oumoussa98** [comment]
You have already defined a default slot and anything else outside will be ignored cause it's also considered a "default slot"

you can put the infinite loading inside the template to fix this problem, but if the `masonry-wall` is iterating over some data and provides a slot for rendering each item which looks like the case in this example, you should define a new slot for the infinite loading and then use it like so

```html
<masonry-wall .....>
    <template #default={item}>
         {{item}}
     </template>
     <template #infinite>
         <InfiniteLoading />
     </template>
</masonry-wall>
```
