### ISSUE TITLE
Identifier doesn't trigger reload upon data change

### ISSUE THREAD

**Issue by Dagge11** [oumoussa98/vue3-infinite-loading#66]
I tried to reload the page upon variable change but it doesn't work. I tried with watcher and computed and without it. In Vue2 it worked. What is the exact syntax of an identifier to make it work? I use Vue 3 with Vite + Options API. I have seen your example with Composition API but I don't want to use exclusively Composition API since it doesn't make Vue work faster or more efficient, it only adds to the clutter. As of now I am temporarily refreshing the page with ``location.reload()` upon changing data but triggering identifier it is a more elegant way. So how to do it with Options API, thanks

**Comment by oumoussa98** [comment]
I can't reproduce this issue if you can provide a repro case would help
However here is a working example with options API on [stackblitz](https://stackblitz.com/edit/v3-infinite-loading-tabs-57rkia?file=src%2FApp.vue)

**Comment by Dagge11** [comment]
I have tried it by implementing your example solution (testNumber), but it doesn't work while default infinite loading works normally. I have used both former Vue2 version method $state.loaded() and $state.complete() .. and I have tried only $state.complete() like in your Vue3 version example. Here are most iomportant code snippets, infinite loading component and loader method:

```
</section>

  </div>
  <infinite-loading @infinite="infiniteHandler" :identifier="testNumber" style="text-align: center; margin-bottom: 5px;">
    <template #complete><span>Kraj rezultata</span></template>
    <template #error><span>Nema rezultata</span></template>
  </infinite-loading>
</template>
```
```
import InfiniteLoading from "v3-infinite-loading";
import "v3-infinite-loading/lib/style.css";
import validator from 'validator';
import axios from 'axios';

export default {
  name: 'home',
  data() {
    return {
      raw: [],  // raw ads from the server
      page: 0, // infinite loading page, start with page 0
      loading: false,  // detect whether the page is still loading to display gray img placeholder
      bkgr: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],  // set how many bkgr placeholder images should be displayed
      testNumber: 1
    }
  },
  methods: {
    infiniteHandler($state) {  // infinite scroll at initial page load, load 15 items at a time
      if (!this.raw.length) this.loading = true; // if number of loaded items is greater than 0 don't show loading placeholder anymore

      axios.get('/initial/' + this.page + `?timestamp=${new Date().getTime()}`).then((res) => {  // we send item number, every time added to 'per-page' number
      if (res.data.length) {
        this.loading = false;
        this.raw.push(...res.data);  // add all received arrays with data to already present data in the 'raw' array
        this.page += 15;  // add 'per-page' number. It hjas to work on different page widths, best if items are displayed in pair, even
        $state.complete();  // we have some more data to load
        //$state.loaded();  // we have some more data to load
        } else {
          $state.complete(); // all data have been loaded (no data on the server anymore)
        }
      }).catch((e) => console.log(e));
    },
```
